### ISSUE TITLE
Sizing by attribute should be optional.

### ISSUE THREAD

**Issue by lastobelus** [mazipan/vue-ionicons#16]
Sizing by width / height makes styling by css difficult; also icons don't scale with user style sheets.

width/height bindings should be optional, and the base style be something like:

```css
.ion__svg {
    overflow: visible;
    display: inline-block;
    height: 1em; /* possibly tweaked so icons match typical font x-heights; I use 1.1em along with margin-top: .05em */
    font-size: inherit;
}
```
